services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  app:
    build: .
    container_name: botix
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env

    ports:
      - "8000:8000"
    restart: unless-stopped

    volumes:
      - ./logs:/app/logs


volumes:
  rabbitmq-data: